### ISSUE TITLE
Week 4

### ISSUE THREAD

**Issue by jvjohnson1** [mad-java-ent-f21/NoFlyTravelPlanner#4]
@pawaitemadisoncollege 
I think I have everything required for week 4 except the journal.  As stated in email, not keeping a daily record of how far I'm falling behind is a conscious decision to protect my mental health.  
Learned - that success in any field depends on finding the required information in an accessible format.  Some websites are accessible and some are not.  That reality means that it takes me longer to find some details because the most frequently used sites are not accessible.  Worse, the visual differences between sites results in a sensory overload and extreme fatigue when searching through multiple sites.  What I need to learn is where to find essential information on accessible sites, so I an spend as much time on this as other students.
Challenge - catching up.  That's obvious.  Meeting the journal requirement when I haven't been keeping records sense week 3.
Blockers - a detail, often small, that is not provided by any accessible site.  Course requirements dictate that I somehow find it with only hints, so I can stay stuck on the same tiny bug for a week or more.

**Comment by pawaitemadisoncollege** [comment]
@jvjohnson1 It's very unfortunate that you aren't willing or able to to log your problem solving process. A large part a software developer's life is troubleshooting (often days and days!). A big part of this course is practicing just that, and fine-tuning that process. It's very difficult for me to help you tweak that process when I'm not able to see what that process is. Remember, the recommended starting approach is this: http://paulawaite.com/education/java113/problemSolvingAndGettingHelp.html. There you can see that internet searching should be one of the _last_ things you use do troubleshoot.   

- [x] For week 4 work, please include a screenshot showing the unit tests passing.
- [x] it looks like an odd $log directory was added to GitHub. This is likely due to this line: https://github.com/mad-java-ent-f21/NoFlyTravelPlanner/blob/c3bb51883a5d3f349bb3b225769d9cb596e17844/src/main/resources/log4j2.properties#L12. There is no `log` property defined.
- [x] It looks like the target directory is still showing up in GitHub -  there's no need to have compiled code versioned. This will make identifying changes made in each commit much more difficult, as the number of files changed in the target directory will always be very high. 
- [x] Package names should contain only lowercase letters: https://github.com/mad-java-ent-f21/NoFlyTravelPlanner/blob/c3bb51883a5d3f349bb3b225769d9cb596e17844/src/main/java/com/jvjohnson1/NoFly/Controller/SearchUser.java#L1
- [x] Does this method really work? I would expect a transaction here similar to delete and insert: https://github.com/mad-java-ent-f21/NoFlyTravelPlanner/blob/c3bb51883a5d3f349bb3b225769d9cb596e17844/src/main/java/com/jvjohnson1/NoFly/persistence/UserDao.java#L33-L40
- [x] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/mad-java-ent-f21/NoFlyTravelPlanner/blob/c3bb51883a5d3f349bb3b225769d9cb596e17844/src/test/java/com/jvjohnson1/NoFly/persistence/UserDaoTest.java#L51

**Comment by jvjohnson1** [comment]
Not sure how we are supposed to use the assertTrue and equals() method, because according to https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html the equals() method returns "true if and only if  this method returns true if and only if x and y refer to the same object (x == y has the value true)."

**Comment by jvjohnson1** [comment]
@pawaitemadisoncollege Other then the comment above, I think I got this one.

**Comment by pawaitemadisoncollege** [comment]
- [x] You will need to override the equals method in the entities. Refer to the video in week 5
<img width="1222" alt="Screen Shot 2021-10-19 at 7 11 58 AM" src="https://user-images.githubusercontent.com/13874466/137906865-0ef1003d-4e04-4ae8-81ba-f7f86a9e3d2b.png">
 - [ ] The logs directory is still in GitHub, please delete it. 
<img width="1279" alt="Screen Shot 2021-10-19 at 7 13 28 AM" src="https://user-images.githubusercontent.com/13874466/137907160-4590d838-bf10-4c9d-a3ae-4ef066dbef8d.png">

 - [x] Missing screenshot showing all unit tests passing

**Comment by jvjohnson1** [comment]
I think I got this issue - I'll be checking through them one at a time.

**Comment by pawaitemadisoncollege** [comment]
I still see the log directory, and do not see a screenshot showing all tests are passing (green).

**Comment by jvjohnson1** [comment]
I'm not sure what needs to be changed in the log directory, but the screenshot with the green checkmarks pushed successfully on the third try.

**Comment by pawaitemadisoncollege** [comment]
Screenshot looks good.

The log directory and target directories are still showing up. Delete them, then commit and push! If they continue to showing up after that, refer back to the suggestions earlier in this issue and in slack with regard to fixing them.

**Comment by jvjohnson1** [comment]
I think we are good to go on this one.

**Comment by pawaitemadisoncollege** [comment]
That's better!
